#!/usr/bin/env ruby
#
# Derived from https://github.com/radiospiel/inspector

# -- A rack application -------------------------------------------------------

require "rack"

def format_hash(hash)
  hash.to_a.
    sort_by(&:first).map do |key, value| 
      "%25s: %s\n" % [ key.to_s.gsub(/^HTTP_/, ""), value.inspect ] 
    end.
    join
end

def insp(env)
  request = Rack::Request.new(env)
  headers, process_env = env.partition do |k,v| k =~ /^HTTP_/ end
  [
    "# Request\n\n",
    format_hash(request_method: request.request_method, fullpath: request.fullpath),
    "\n# Headers\n\n",
    format_hash(headers),
    "\n# process environment\n\n",
    format_hash(ENV)
  ].join("\n")
end

Application = proc do |env|
  req = Rack::Request.new(env)
  body = req.path != "/" ? "#{req.request_method} #{req.fullpath}\n" : insp(env)
  
  [
    200, 
    { 'Content-Type' => 'text/plain' }, 
    [ body ]
  ]
end

# -- configure rack server ----------------------------------------------------

require "webrick/https"

RACK_SERVER_OPTIONS = {
  :app => Application,
  :BindAddress => "localhost",
  :Port => ENV["PORT"] || 8080,
  :server => "webrick",
  :Logger => WEBrick::BasicLog.new($stderr, WEBrick::BasicLog::WARN)
}

if $0 == __FILE__
  puts "Starting http server at port #{RACK_SERVER_OPTIONS[:Port]}"
  Rack::Server.start(RACK_SERVER_OPTIONS)
end
